version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Use the variable from .env
      # Add other environment variables here
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]
    # Or if using yarn:
    # command: ["yarn", "dev"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

volumes:
  postgres_data:
